[package]
name = "openscenario-rs"
version = "0.1.0"
edition = "2021"
authors = ["OpenSCENARIO Contributors"]
description = "Rust library for parsing and manipulating OpenSCENARIO files"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-org/openscenario-rs"
keywords = ["openscenario", "xml", "automotive", "simulation", "asam"]
categories = ["parsing", "simulation"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.30", features = ["serialize"] }
thiserror = "1.0"

# Optional dependencies for later phases
indexmap = { version = "2.0", optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
regex = { version = "1.0", optional = true }

[features]
default = ["serde-parsing"]
serde-parsing = []
validation = ["regex", "indexmap"]
builder = []
expressions = ["regex"]
streaming = []
full = ["validation", "builder", "expressions"]

[dev-dependencies]
proptest = "1.0"
criterion = "0.5"
tempfile = "3.0"
serde_json = "1.0.143"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
