[package]
name = "openscenario-rs"
version = "0.1.0"
edition = "2021"
authors = ["Ashfaq Farooqui"]
description = "Rust library for parsing and manipulating OpenSCENARIO files"
license = "GPLv3"
repository = "https://github.com/ashfaqfarooqui/openscenario-rs"
keywords = ["openscenario", "xml", "automotive", "simulation", "asam"]
categories = [""]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.30", features = ["serialize"] }
serde_json = "1.0"
thiserror = "1.0"
async-trait = "0.1"

indexmap = { version = "2.0" }
chrono = { version = "0.4", features = ["serde"] }
regex = { version = "1.0" }


[dev-dependencies]
proptest = "1.0"
criterion = "0.5"
tempfile = "3.0"
serde_json = "1.0.143"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync"] }

[[bin]]
name = "test_param_variation"
path = "test_param_variation.rs"

[[bin]]
name = "debug_parse_variation"
path = "debug_parse_variation.rs"

[[bin]]
name = "simple_test"
path = "simple_test.rs"


